/*
Exports some utility functions which are used for automatic code generation.
*/

import * as fs from 'fs';
import { argv } from 'process';

/*
Generates a file with the given content at the given path.
Adds a warning at the top that the file is automatically generated
and should not be edited. Includes a reference to the script
which generated it.
*/
export function generateFile(filePath: string, fileContents: string): void {
  const referenceScript = argv[1];
  const plainReferenceScript = referenceScript.slice(
    referenceScript.lastIndexOf('/') + 1
  );

  const fileContentsWithWarning = `
/*
ATTENTION: DO NOT EDIT
This file is automatically generated.
See script: ${plainReferenceScript}
*/
${fileContents}
`;

  fs.writeFileSync(addAutogenSuffix(filePath), fileContentsWithWarning);
}

/*
file.ext --> file.autogen.ext
*/
export function addAutogenSuffix(filePath: string): string {
  const indexOfLastDot = filePath.lastIndexOf('.');
  const filePathWithSuffix =
    filePath.slice(0, indexOfLastDot) +
    '.autogen' +
    filePath.slice(indexOfLastDot);
  return filePathWithSuffix;
}
